print("Vipul car rental")
print("Main menu")
print("01:- BMW")
print("02:- Mercedes")
print("03:- Audi")
print("04:- Hyundai")
print("05:- Honda")
print("06:- skoda")
print("07:- Ford")
print("08:- Tyota")

caroption=int(input("enter your choice for 1-8 = "))
if caroption==1:
    print("Thanks for choosing BMW for further booking continue")
    Name = input("Enter your full name = ")
    date=int(input("from and till date = "))
    desinationlocation = input("enter you location you want to go = ")
    deparutelocation=input("enter the location from where you want to go = ")
    mobileno = input("enter your mobile no for linkin it with you account no = ")
    print("Thanks", Name ,"for booking BMW for your booking on", date,"from ", deparutelocation ,"to", desinationlocation,"you will also get a confirmation messgae of your registered mobile no =",mobileno)
    print("price for bmw price for every hour is 600rs ")
elif caroption==2:
    print("Thanks for choosing Mercedes for further booking continue ")
    Name = input("Enter your full name = ")
    date=int(input("from and till date = "))
    desinationlocation = input("enter you location you want to go = ")
    deparutelocation=input("enter the location from where you want to go = ")
    mobileno = input("enter your mobile no for linkin it with you account no = ")
    print("Thanks", Name ,"for booking Mercedes for your booking on", date,"from ", deparutelocation ,"to", desinationlocation,"you will also get a confirmation messgae of your registered mobile no =",mobileno)
    print("price for Mercedes price for every hour is 650rs ")
elif caroption==3:
    print("Thanks for choosing Audi for further booking continue")
    Name = input("Enter your full name = ")
    date=int(input("from and till date = "))
    desinationlocation = input("enter you location you want to go = ")
    deparutelocation=input("enter the location from where you want to go = ")
    mobileno = input("enter your mobile no for linkin it with you account no = ")
    print("Thanks", Name ,"for booking Audi for your booking on", date,"from ", deparutelocation ,"to", desinationlocation,"you will also get a confirmation messgae of your registered mobile no =",mobileno)
    print("price for Audi price for every hour is 800rs ")
elif caroption==4:
    print("Thanks for choosing Hyundai for further booking continue")
    Name = input("Enter your full name = ")
    date=int(input("from and till date = "))
    desinationlocation = input("enter you location you want to go = ")
    deparutelocation=input("enter the location from where you want to go = ")
    mobileno = input("enter your mobile no for linkin it with you account no = ")
    print("Thanks", Name ,"for booking Hyundai for your booking on", date,"from ", deparutelocation ,"to", desinationlocation,"you will also get a confirmation messgae of your registered mobile no =",mobileno)
    print("price for Hyundai price for every hour is 300rs ")
elif caroption==5:
    print("Thanks for choosing Honda for further booking continue")
    Name = input("Enter your full name = ")
    date=int(input("from and till date = "))
    desinationlocation = input("enter you location you want to go = ")
    deparutelocation=input("enter the location from where you want to go = ")
    mobileno = input("enter your mobile no for linkin it with you account no = ")
    print("Thanks", Name ,"for booking Honda for your booking on", date,"from ", deparutelocation ,"to", desinationlocation,"you will also get a confirmation messgae of your registered mobile no =",mobileno)
    print("price for Honda price for every hour is 350rs ")
elif caroption==6:
    print("Thanks for choosing Skoda for further booking continue")
    Name = input("Enter your full name = ")
    date=int(input("from and till date = "))
    desinationlocation = input("enter you location you want to go = ")
    deparutelocation=input("enter the location from where you want to go = ")
    mobileno = input("enter your mobile no for linkin it with you account no = ")
    print("Thanks", Name ,"for booking Skoda for your booking on", date,"from ", deparutelocation ,"to", desinationlocation,"you will also get a confirmation messgae of your registered mobile no =",mobileno)
    print("price for Skoda price for every hour is 400rs ")
elif caroption==7:
    print("Thanks for choosing Ford for further booking continue")
    Name = input("Enter your full name = ")
    date=int(input("from and till date = "))
    desinationlocation = input("enter you location you want to go = ")
    deparutelocation=input("enter the location from where you want to go = ")
    mobileno = input("enter your mobile no for linkin it with you account no = ")
    print("Thanks", Name ,"for booking Ford for your booking on", date,"from ", deparutelocation ,"to", desinationlocation,"you will also get a confirmation messgae of your registered mobile no =",mobileno)
    print("price for Ford price for every hour is 450rs ")
elif caroption==8:
    print("Thanks for choosing Toyota for further booking continue")
    Name = input("Enter your full name = ")
    date=int(input("from and till date = " ))
    desinationlocation = input("enter you location you want to go = ")
    deparutelocation=input("enter the location from where you want to go = ")
    mobileno = input("enter your mobile no for linkin it with you account no = ")
    print("Thanks", Name ,"for booking Toyota for your booking on", date,"from ", deparutelocation ,"to", desinationlocation,"you will also get a confirmation messgae of your registered mobile no =",mobileno)
    print("price for Toyota price for every hour is 500rs ")